### ISSUE TITLE
poolSize can't be set to 0

### ISSUE THREAD

**Issue by alecapu80** [merterkoc/mongo_pool#10]
Hi
why don't you permit to set poolSize to 0?
With poolSize>0 we mush have at least one connection always active although we don't need it.
Furthermore, if you use a Mongo configuration for enterprise (like for example Mongo Atlas) it is good practice to force server-side closure of connections that are inactive for more than X amount of time. If this happens the pool would find itself with connections that have actually been closed from server.
What happens if a pool connection is closed (server side or network connection goes down)? during the acquire phase, is it checked that the connection is still up?

**Comment by merterkoc** [comment]
Hello,
mongo_pool opens connections using the mongo_dart package developed for dart. This package manages the connections opened within itself. However, as you said, it would be useful to make an improvement for this. I will make an improvement for this.
Closing connections that have not been used for a long time is a behavior outside the main purpose of the package. The connection pool should always keep the specified amount of connections open for requests that will arrive at time T. This is necessary to respond to requests faster. Mongo_dart should manage the unexpected closure of these connections within itself.
Pool Size is the specified minimum number of connections. This cannot be less than 1.

**Comment by merterkoc** [comment]
> Hi why don't you permit to set poolSize to 0? With poolSize>0 we mush have at least one connection always active although we don't need it. Furthermore, if you use a Mongo configuration for enterprise (like for example Mongo Atlas) it is good practice to force server-side closure of connections that are inactive for more than X amount of time. If this happens the pool would find itself with connections that have actually been closed from server. What happens if a pool connection is closed (server side or network connection goes down)? during the acquire phase, is it checked that the connection is still up?

Hello,
As of version 1.5.1, poolSize can now be set to 0, enabling lazy connection creation (no connections are opened until first acquire).

Thanks!
