### ISSUE TITLE
Problem with closed connection

### ISSUE THREAD

**Issue by Oskar888** [merterkoc/mongo_pool#9]
I have a problem because from time to time I get this error: "MongoDB ConnectionException: connection closed: The socket connection has been reset by peer.", it doesn't always happen, but as I mentioned, sometimes.

**Comment by Oskar888** [comment]
I will add that the problem does not appear during connection, only when performing some operation on mongoDB, e.g. update

**Comment by merterkoc** [comment]
Hello, I think your problem is related to [this](https://stackoverflow.com/questions/76022120/mongodb-error-connection-closed-in-flutter). Some methods are deprecated. Can you try using alternative methods?
i will be waiting for your feedback.

**Comment by merterkocfinkoto** [comment]
Is this problem still occurring?

**Comment by merterkoc** [comment]
If there are no other answers to this issue, I'm marking it as solved.
